### ISSUE TITLE
limited items and "touch" issue

### ISSUE THREAD

**Issue by ghost** [fengberd/FChestReset#2]
well, the plugin works fine, but I had some issues...
- I can put thousands of items on config file, but the plugin only catches the first ones, Only less than 10 items are really used for refill...
- the 9 - 12 chests that I configured for first, is sucessfully refiled, but more that that, the players can't open the chest... when the player touch the chest, the chest disappear!

large hunger games maps require a lot of chests, so, please take a lock into this issue if possible :)

thank you!

**Comment by fengberd** [comment]
Sorry,I'll never update it,but you can fix these bugs by yourself.To fix them,you should rewrite some method but it's not very difficult.
